### ISSUE TITLE
[US] Programm Page

### ISSUE THREAD

**Issue by KoglerT** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-android#35]
# Description
As User i want to see the event List on Samstag/Sonntag [#31] , the filterbar [#32],  on the programm page

# Acceptance criteria
All other implemented pages and list of events are shown

# Possible way to test
Test with Emulator

# Dependencies
- requires #31, #32, #48

**Comment by dev-Fabi** [comment]
Is already part of 
- #31 
- #32

**Comment by dev-Fabi** [comment]
Is already part of
- #31
- #32
