### ISSUE TITLE
[T] Voting Business logic

### ISSUE THREAD

**Issue by dev-Fabi** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-android#69]
# Description
This task will add the business logic for the voting feature (VotingViewModel, ...).

There are 5 states for the voting which must be represented and exposed to the UI:
- ~Voting has not stated yet~
- Voting is ongoing (user has not voted yet)
- Voting is ongoing (user has already voted)
- ~Voting is closed but winner isn't announced yet~
- ~Voting is closed and winner is announced~
- Voting currently not possible (not active)

# Acceptance criteria
- Vote is persisted
- User can only vote once (and not change)
- User can only vote when voting is enabled
- User can only vote for "events" which are vote-able

# Requirement for
- #80 
- #81 
- #82

**Comment by adamkhalil1** [comment]
@dev-Fabi please have a look at merge request #81 had some issues with business logic
