### ISSUE TITLE
[T] Voting Card UI Component

### ISSUE THREAD

**Issue by dev-Fabi** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-android#84]
# Description
This task will add the UI component for the Voting.

# Acceptance criteria
- Uses a Card
- Title, Image and description is shown

<img width="300" src="https://user-images.githubusercontent.com/73596295/234227631-85bef900-5084-4f55-bbbe-2447ccb48765.png">

Also see #34 (#75)

**Comment by adamkhalil1** [comment]
please Stop any development there
